from langchain_core.messages import SystemMessage
from langgraph.graph import END
from utils import llm
import json

def report_generator_agent(state):
    print(f"\n📝 REPORT GENERATOR AGENT ACTIVATED")
    print(f"   Standardizing output and generating actions...")
    
    messages = state["messages"]
    # Get the response generated by the specialist agent (Cyber/Scam/Civil)
    final_response = state.get("final_response", "")
    
    if not final_response:
        # Fallback if no response exists
        final_response = messages[-1].content if messages else "No info available."

    # System Prompt to Extract Structured Data
    system_prompt = f"""You are the Report Generator Agent.
    Your task is to analyze the conversation and the AI's response to generate a STRUCTURED JSON REPORT.
    
    AI RESPONSE TO ANALYZE:
    {final_response}
    
    TASK:
    Generate a JSON object with:
    1. 'incident_type': specific category (e.g., Financial Fraud, Identity Theft, General Query).
    2. 'risk_level': 'High' (Financial loss/Imminent threat), 'Medium', or 'Low'.
    3. 'cognizable': boolean, true if the offense is cognizable based on the AI response's classification tags.
    4. 'is_complex_mlat': boolean, true if it involves MLATs or complex treaties based on classification tags.
    5. 'fraud_under_10k': boolean or null, true if explicitly stated fraud is < 10,000 INR, false if > 10,000, null if NA.
    6. 'summary': Brief summary of the issue (1-2 sentences). **IF LOCAL SCAM WARNING WAS MENTIONED, INCLUDE IT IN THE SUMMARY**.
    7. 'statutory_sections': List of laws mentioned (e.g., "IT Act Section 66C").
    8. 'checklist': List of 3-4 immediate steps from the response. **IF LOCAL SCAM WAS MENTIONED, ADD A STEP TO VERIFY IT.**
    
    Output MUST be valid JSON only. Do not wrap in code blocks.
    """
    
    try:
        response = llm.invoke([SystemMessage(content=system_prompt)] + messages)
        
        # Extract string from response.content in case it's a multimodal list block
        content = response.content
        if isinstance(content, list):
            content = "".join([c.get("text", "") if isinstance(c, dict) else str(c) for c in content])
        elif not isinstance(content, str):
            content = str(content)
            
        # Clean response string to ensure JSON parsing
        content = content.strip()
        if content.startswith("```json"):
            content = content[7:-3]
        elif content.startswith("```"):
            content = content[3:-3]
            
        data = json.loads(content)
        
        structured_report = {
            "incident_type": data.get("incident_type", "General"),
            "risk_level": data.get("risk_level", "Low"),
            "cognizable": data.get("cognizable", False),
            "is_complex_mlat": data.get("is_complex_mlat", False),
            "fraud_under_10k": data.get("fraud_under_10k", None),
            "summary": data.get("summary", ""),
            "statutory_sections": data.get("statutory_sections", []),
            "checklist": data.get("checklist", [])
        }
        
        # Determine Criticality & Routing
        # High Criticality: High Risk + Cognizable + MLAT/Complex
        # Small Matters: Fraud < 10k or Low Risk
        actions = []
        risk = structured_report["risk_level"]
        incident = structured_report["incident_type"].lower()
        cognizable = structured_report["cognizable"]
        is_complex = structured_report["is_complex_mlat"]
        fraud_under_10k = structured_report["fraud_under_10k"]
        
        # Route to legal_moderator by default if High Criticality
        next_step = END
        criticality = "Low/Unknown"
        
        if risk == "High" and cognizable and is_complex:
            criticality = "High Criticality"
            next_step = "legal_moderator"
            structured_report["criticality"] = criticality
        elif fraud_under_10k is True or risk == "Low":
            criticality = "Moderate Criticality (Small Matter)"
            structured_report["criticality"] = criticality
        else:
            criticality = "Moderate Criticality"
            structured_report["criticality"] = criticality
        
        # Dynamic Actions based on Risk & Content
        actions = []
        risk = structured_report["risk_level"]
        incident = structured_report["incident_type"].lower()
        
        if criticality == "High Criticality":
            actions.append({"label": "Contact Bank immediately", "action": "show_helpline", "payload": "1930"})
        
        if "fraud" in incident or "scam" in incident:
             actions.append({"label": "File Complaint Guide", "action": "show_guide", "payload": "cyber_crime_steps"})
        
        # Default action
        actions.append({"label": "Connect to Nyay Guide", "node": "sahayak", "payload": "Request Human Help"})

        # Append satisfaction check if NOT going to legal moderator
        if next_step == END:
            final_response += "\n\n***\n**Are you satisfied with this response?**\n*If not, you can ask for a lawyer suggestion or request to be assigned a Nyaysahayak (human).* "

        return {
            "structured_report": structured_report,
            "suggested_actions": actions,
            "final_response": final_response, # Update state with the appended text
            "next_step": next_step
        }
        
    except Exception as e:
        print(f"❌ Error in Report Generator: {e}")
        return {
            "structured_report": {"error": "Failed to generate report"}, 
            "suggested_actions": [{"label": "Talk to Human", "node": "sahayak"}],
            "next_step": END
        }
